"""Scenario table used to generate and describe training messages: (urgency, specialist id, situation).
Written by hand. The wording of the generated messages comes from an LLM; the LABELS come from this table,
so every generated row is marked synthetic."""

SCENARIOS = [
    # ---- emergency
    ("emergency", "cardiologist", "crushing chest pain or pressure spreading to the left arm or jaw with sweating"),
    ("emergency", "cardiologist", "sudden racing heartbeat with fainting or near-fainting"),
    ("emergency", "neurologist", "face drooping, slurred speech, one arm suddenly weak (stroke signs)"),
    ("emergency", "neurologist", "sudden worst headache of life with vomiting and neck stiffness"),
    ("emergency", "neurologist", "seizure that is not stopping, or repeated seizures without waking"),
    ("emergency", "pulmonologist", "cannot breathe, gasping, lips or fingers turning blue"),
    ("emergency", "pulmonologist", "severe asthma attack not relieved by the inhaler, cannot speak a full sentence"),
    ("emergency", "general_physician", "fainted at home and is not waking up properly"),
    ("emergency", "general_physician", "heavy bleeding from a wound that will not stop with pressure"),
    ("emergency", "general_physician", "swollen tongue or throat tightness and hives after taking a new medicine or insect sting"),
    ("emergency", "diabetologist", "very low sugar: shaking, sweating, confused or unconscious after insulin or tablets"),
    ("emergency", "diabetologist", "blood sugar above 500 with drowsiness, fruity breath, fast breathing"),
    ("emergency", "gastroenterologist", "vomiting blood or passing black tarry stools with dizziness"),
    ("emergency", "paediatrician", "a baby or small child who is limp, not responding, or struggling to breathe"),
    ("emergency", "psychiatrist", "says they want to end their life and have a plan"),
    # ---- urgent
    ("urgent", "general_physician", "high fever 102 to 104 for three days with shivering and body pain"),
    ("urgent", "general_physician", "fever with severe joint pain, rash and weakness after mosquito bites (dengue-like)"),
    ("urgent", "paediatrician", "a child with fever for three days who is not eating or drinking much"),
    ("urgent", "gastroenterologist", "vomiting many times since night and cannot keep water down"),
    ("urgent", "gastroenterologist", "severe pain in the upper right belly with yellow eyes and dark urine"),
    ("urgent", "ophthalmologist", "sudden blurry or lost vision in one eye"),
    ("urgent", "ophthalmologist", "eye injury with pain and redness after something hit the eye"),
    ("urgent", "orthopaedician", "severe lower back pain so bad cannot stand straight, pain going down the leg"),
    ("urgent", "orthopaedician", "swollen painful ankle after a fall and cannot put weight on it"),
    ("urgent", "diabetologist", "sugar reading above 350 with heavy thirst and passing a lot of urine"),
    ("urgent", "diabetologist", "a foot wound in a diabetic that is red, swollen and not healing"),
    ("urgent", "urologist", "severe pain in the side with blood in the urine"),
    ("urgent", "urologist", "has not been able to pass urine for many hours"),
    ("urgent", "nephrologist", "swelling of both feet and face with very little urine"),
    ("urgent", "pulmonologist", "cough with fever and breathlessness for five days"),
    ("urgent", "cardiologist", "blood pressure 190/110 with a pounding headache"),
    ("urgent", "cardiologist", "new leg swelling and breathlessness when lying flat"),
    ("urgent", "ent", "ear pain with discharge and fever"),
    ("urgent", "ent", "sore throat so painful that swallowing even water is hard, with fever"),
    ("urgent", "neurologist", "spinning dizziness with repeated vomiting that began suddenly"),
    ("urgent", "gynaecologist", "pregnant and having vaginal bleeding or severe abdominal pain"),
    ("urgent", "dermatologist", "spreading red, hot, swollen skin with fever"),
    # ---- routine
    ("routine", "orthopaedician", "knee pain when climbing stairs for a few weeks"),
    ("routine", "orthopaedician", "neck and shoulder pain from long hours at a desk"),
    ("routine", "dermatologist", "itchy red patches on the skin for a week or two"),
    ("routine", "dermatologist", "acne or hair fall that has been going on for months"),
    ("routine", "pulmonologist", "dry cough for ten days, worse at night, no fever"),
    ("routine", "cardiologist", "blood pressure check and medicine refill"),
    ("routine", "diabetologist", "regular sugar review, HbA1c test and medicine refill"),
    ("routine", "gastroenterologist", "burning and acidity after meals for several weeks"),
    ("routine", "gastroenterologist", "constipation for a week or more"),
    ("routine", "endocrinologist", "feeling tired and gaining weight, wants a thyroid check"),
    ("routine", "ent", "blocked nose and mild ear pain for four days"),
    ("routine", "ophthalmologist", "wants an eye test because reading has become difficult"),
    ("routine", "dentist", "toothache for three days or bleeding gums"),
    ("routine", "psychiatrist", "stress and poor sleep for the past month"),
    ("routine", "gynaecologist", "irregular periods for a few months"),
    ("routine", "urologist", "burning while passing urine for two days, no fever"),
    ("routine", "urologist", "has to get up three or four times at night to pass urine (older man)"),
    ("routine", "neurologist", "headaches that keep coming back every week"),
    ("routine", "nephrologist", "kidney test follow-up and diet advice"),
    ("routine", "haematologist", "tiredness and looking pale, wants a blood count check"),
    ("routine", "general_physician", "general health check-up, no complaints"),
    ("routine", "general_physician", "body ache and low energy for a week without fever"),
    ("routine", "paediatrician", "child with a cold for three days, playing and eating normally; also vaccine question"),
    # ---- self care
    ("self_care", "general_physician", "mild runny nose and sneezing since yesterday"),
    ("self_care", "general_physician", "slight sore throat and feeling a bit tired today"),
    ("self_care", "general_physician", "mild cough for one day, no fever"),
    ("self_care", "neurologist", "slight headache after a long tiring day"),
    ("self_care", "dermatologist", "a small scratch or mild sunburn"),
    ("self_care", "gastroenterologist", "mild gas or bloating after a heavy meal"),
    ("self_care", "orthopaedician", "minor muscle ache after exercise or carrying heavy bags"),
]
