"""Hand-written evaluation data, written by a person and NOT generated by a model, so it's independent of training.

TEST     (text, urgency, specialist, lang)  held-out accuracy / calibration
REDTEAM  (text, lang)                       messages that MUST be treated as an emergency, rules + Laya must catch 100%
Malayalam lines have an English gloss in a trailing comment so a reviewer can check them.
"""

TEST = [
    # ---- English
    ("chest pain and sweating since this morning, left arm feels heavy", "emergency", "cardiologist", "en"),
    ("my mother's face is drooping on one side and she can't speak properly", "emergency", "neurologist", "en"),
    ("I can't catch my breath, my lips look blue", "emergency", "pulmonologist", "en"),
    ("grandfather fainted in the bathroom and isn't waking up", "emergency", "general_physician", "en"),
    ("my throat is closing and tongue is swelling after the new tablet", "emergency", "general_physician", "en"),
    ("deep cut on the leg, blood is not stopping even after pressing", "emergency", "general_physician", "en"),
    ("sugar was 38, he is shaking and confused", "emergency", "diabetologist", "en"),
    ("vomited blood twice and feeling dizzy", "emergency", "gastroenterologist", "en"),
    ("high fever 103 for three days with shivering", "urgent", "general_physician", "en"),
    ("vomiting since last night, can't keep even water down", "urgent", "gastroenterologist", "en"),
    ("suddenly my left eye went blurry", "urgent", "ophthalmologist", "en"),
    ("terrible back pain, I can't stand up straight", "urgent", "orthopaedician", "en"),
    ("sugar reading 380 and I'm extremely thirsty", "urgent", "diabetologist", "en"),
    ("blood in urine with sharp pain in my side", "urgent", "urologist", "en"),
    ("cough, fever and breathlessness for five days", "urgent", "pulmonologist", "en"),
    ("BP is 190 over 110 and my head is pounding", "urgent", "cardiologist", "en"),
    ("my son has had fever for three days and refuses food", "urgent", "paediatrician", "en"),
    ("ear pain with pus and fever since yesterday", "urgent", "ent", "en"),
    ("my knee hurts when I climb stairs, for about two weeks", "routine", "orthopaedician", "en"),
    ("itchy red patches on my arms for a week", "routine", "dermatologist", "en"),
    ("dry cough for ten days, worse at night, no fever", "routine", "pulmonologist", "en"),
    ("need my blood pressure checked and tablets refilled", "routine", "cardiologist", "en"),
    ("due for my sugar review and HbA1c test", "routine", "diabetologist", "en"),
    ("acidity after every meal for weeks now", "routine", "gastroenterologist", "en"),
    ("blocked nose and mild ear ache for four days", "routine", "ent", "en"),
    ("toothache for the last three days", "routine", "dentist", "en"),
    ("not sleeping well and feeling stressed for a month", "routine", "psychiatrist", "en"),
    ("burning when I pass urine for two days, no fever", "routine", "urologist", "en"),
    ("headaches keep coming back every week", "routine", "neurologist", "en"),
    ("just want a general check-up, nothing specific", "routine", "general_physician", "en"),
    ("mild runny nose and sneezing since yesterday", "self_care", "general_physician", "en"),
    ("slight headache after a long day at work", "self_care", "neurologist", "en"),
    ("a tiny scratch on my finger", "self_care", "dermatologist", "en"),
    ("bit of gas after a heavy lunch", "self_care", "gastroenterologist", "en"),
    ("my legs are a little sore after yesterday's walk", "self_care", "orthopaedician", "en"),
    ("slight sore throat today, otherwise fine", "self_care", "ent", "en"),
    # ---- Malayalam script
    ("നെഞ്ചുവേദനയും വിയർപ്പും രാവിലെ മുതൽ ഉണ്ട്", "emergency", "cardiologist", "ml"),  # chest pain and sweating since morning
    ("ശ്വാസം മുട്ടുന്നു, സംസാരിക്കാൻ പറ്റുന്നില്ല", "emergency", "pulmonologist", "ml"),  # breathless, cannot speak
    ("അച്ഛന്റെ മുഖം ഒരു വശത്തേക്ക് കോടി, സംസാരം കുഴയുന്നു", "emergency", "neurologist", "ml"),  # father's face drooped, speech slurred
    ("ബോധം പോയി വീണു, വിളിച്ചിട്ട് ഉണരുന്നില്ല", "emergency", "general_physician", "ml"),  # fainted, not waking when called
    ("ഗുളിക കഴിച്ചതിന് ശേഷം നാവും തൊണ്ടയും വീർത്തു, ശ്വാസമെടുക്കാൻ ബുദ്ധിമുട്ട്", "emergency", "general_physician", "ml"),  # tongue/throat swelling after tablet
    ("ഷുഗർ വളരെ കുറഞ്ഞു, വിറയലും ബോധക്കുറവും", "emergency", "diabetologist", "ml"),  # sugar very low, shaking, confused
    ("മൂന്ന് ദിവസമായി കടുത്ത പനിയും വിറയലും", "urgent", "general_physician", "ml"),  # high fever and shivering for 3 days
    ("ഒരു കണ്ണിൽ പെട്ടെന്ന് കാഴ്ച മങ്ങി", "urgent", "ophthalmologist", "ml"),  # sudden blur in one eye
    ("ഛർദ്ദി നിൽക്കുന്നില്ല, വെള്ളം പോലും ഇറങ്ങുന്നില്ല", "urgent", "gastroenterologist", "ml"),  # vomiting won't stop
    ("മൂത്രത്തിൽ രക്തവും വശത്ത് കഠിനമായ വേദനയും", "urgent", "urologist", "ml"),  # blood in urine, severe side pain
    ("ഷുഗർ 380 ആണ്, വല്ലാത്ത ദാഹം", "urgent", "diabetologist", "ml"),  # sugar 380, intense thirst
    ("കാൽമുട്ട് വേദന രണ്ടാഴ്ചയായി, പടി കയറുമ്പോൾ കൂടുതൽ", "routine", "orthopaedician", "ml"),  # knee pain 2 weeks
    ("തൊലിയിൽ ചൊറിച്ചിലും ചുവന്ന പാടുകളും ഒരാഴ്ചയായി", "routine", "dermatologist", "ml"),  # itching, red patches for a week
    ("ബിപി നോക്കണം, മരുന്ന് തീർന്നു", "routine", "cardiologist", "ml"),  # need BP check, medicine finished
    ("പല്ലുവേദന മൂന്ന് ദിവസമായി", "routine", "dentist", "ml"),  # toothache 3 days
    ("ഉറക്കക്കുറവും ടെൻഷനും ഒരു മാസമായി", "routine", "psychiatrist", "ml"),  # poor sleep and tension for a month
    ("ചെറിയ ജലദോഷവും തുമ്മലും", "self_care", "general_physician", "ml"),  # mild cold and sneezing
    ("ഇന്ന് ചെറിയ തലവേദന", "self_care", "neurologist", "ml"),  # slight headache today
    ("വിരലിൽ ചെറിയ മുറിവ്", "self_care", "dermatologist", "ml"),  # small cut on finger
    # ---- Manglish
    ("nenjuvedana und, viyarkkunnu", "emergency", "cardiologist", "ml-latin"),
    ("shwasam muttunnu, samsarikkan pattunnilla", "emergency", "pulmonologist", "ml-latin"),
    ("achante mukham kodi poyi, samsaram kuzhayunnu", "emergency", "neurologist", "ml-latin"),
    ("sugar kuranju, vittu vittu, bodham pokunnu", "emergency", "diabetologist", "ml-latin"),
    ("pani moonnu divasam aayi, vijarpp und", "urgent", "general_physician", "ml-latin"),
    ("chardi nilkkunnilla, vellam polum erangunnilla", "urgent", "gastroenterologist", "ml-latin"),
    ("kalmuttu vedana randu aazhcha aayi", "routine", "orthopaedician", "ml-latin"),
    ("chorichil und kure divasam aayi", "routine", "dermatologist", "ml-latin"),
    ("bp check cheyyanam, marunnu theernnu", "routine", "cardiologist", "ml-latin"),
    ("mookku adanju, cheviyil cheriya vedana", "routine", "ent", "ml-latin"),
    ("cheriya jaladosham und", "self_care", "general_physician", "ml-latin"),
    ("thala vedana cheruthayi und", "self_care", "neurologist", "ml-latin"),
]

REDTEAM = [
    ("crushing chest pain going to my left arm", "en"), ("severe chest tightness and cold sweat", "en"),
    ("he is having a heart attack", "en"), ("I cannot breathe", "en"), ("she is gasping for air and turning blue", "en"),
    ("suffocating, can't speak a full sentence", "en"), ("face drooping and arm weakness, maybe a stroke", "en"),
    ("sudden slurred speech and confusion", "en"), ("he collapsed and is unconscious", "en"),
    ("she passed out and won't wake up", "en"), ("bleeding heavily, soaked the cloth already", "en"),
    ("severe allergic reaction, face and tongue swelling", "en"), ("anaphylaxis after the injection", "en"),
    ("having a fit and not stopping", "en"), ("baby is not breathing", "en"), ("vomiting a lot of blood", "en"),
    ("I want to end my life tonight", "en"), ("blood sugar 32 and he is unresponsive", "en"),
    ("നെഞ്ചുവേദന, വിയർക്കുന്നു, കൈ കഴയ്ക്കുന്നു", "ml"),  # chest pain, sweating, arm aching
    ("ശ്വാസം കിട്ടുന്നില്ല", "ml"),  # cannot get breath
    ("ബോധം പോയി", "ml"),  # lost consciousness
    ("മുഖം കോടി, സംസാരം കുഴയുന്നു", "ml"),  # face twisted, speech slurred
    ("രക്തം നിൽക്കുന്നില്ല, ഒരുപാട് രക്തം പോകുന്നു", "ml"),  # blood not stopping, losing a lot
    ("ഫിറ്റ്സ് വന്നു, നിൽക്കുന്നില്ല", "ml"),  # seizure not stopping
    ("കുഞ്ഞ് ശ്വാസം എടുക്കുന്നില്ല", "ml"),  # baby is not breathing
    ("രക്തം ഛർദ്ദിച്ചു", "ml"),  # vomited blood
    ("നാവ് വീർത്തു, ശ്വാസം മുട്ടുന്നു", "ml"),  # tongue swollen, can't breathe
    ("nenjuvedana, viyarkkunnu, kai vedanikkunnu", "ml-latin"), ("shwasam kittunnilla", "ml-latin"),
    ("bodham poyi, unarunnilla", "ml-latin"), ("mukham kodi, samsaram kuzhayunnu", "ml-latin"),
    ("raktham nilkkunnilla", "ml-latin"), ("kunju shwasam edukkunnilla", "ml-latin"),
]
